{% set name = "pyhdx" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyHDX-{{ version }}.tar.gz
  sha256: a018d79ab37f552f46bfb87f04d0316899a07a2d6205298eea0f461e1b1e53db

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python
  run:
    - bokeh
    - dask
    - hdxrate >=0.2.0
    - matplotlib-base
    - numpy
    - pandas
    - panel >=0.10.1
    - param
    - pbr  # [( py<38 )]
    - pytorch
    - python
    - scikit-image
    - scipy
    - symfit
    - tqdm

test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
