{% set name = "pyhdx" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b447d9f71021db7cc697bed6dce566c35b3867993ad76dc0c35d358f58c6131a

build:
  number: 0
  noarch: python
  entry_points:
    - pyhdx = pyhdx.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - hdxrate >=0.2.0
    - numpy
    - matplotlib-base ==3.4.3
    - pandas
    - scikit-image
    - scipy
    - symfit >=0.5.5
    - typer
    - param
    - pytorch
    - omegaconf >=2.2.2
    - tqdm
    - typer
    - dask
    - distributed
    - param
    - packaging
    - panel >=0.13.0
    - bokeh
    - holoviews
    - colorcet >=3.0.0
    - hvplot
    - proplot ==0.9.3
    - pyyaml


test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
