{% set name = "pyhdx" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyHDX-{{ version }}.tar.gz
  sha256: 8be060e467445e4e739f794bf9e570d99dda1d03e3e2813c6898f0b5b634f098

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python
  run:
    - bokeh
    - dask
    - hdxrate >=0.2.0
    - matplotlib-base
    - numpy
    - pandas
    - panel >=0.11.0
    - param
    - pbr
    - pytorch
    - python
    - scikit-image
    - scipy
    - symfit
    - tqdm

test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
