{% set name = "pyhdx" %}
{% set version = "0.4.0b8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyHDX-{{ version }}.tar.gz
  sha256: ef584c5d4b7c5b4069d9566ad4cd93b72c8e9ad280e52b7c68d028cabc3f6e90

build:
  number: 0
  noarch: python
  entry_points:
    - pyhdx = pyhdx.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - hdxrate >=0.2.0
    - numpy
    - matplotlib-base ==3.4.3
    - pandas
    - scikit-image
    - scipy
    - symfit
    - sympy ==1.5.1
    - pytorch
    - tqdm
    - dask
    - distributed
    - packaging
test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
