{% set name = "pyhdx" %}
{% set version = "0.4.0b9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyHDX-{{ version }}.tar.gz
  sha256: 8cbc7e5f26885a94cd59475d798321d48417de41f2d0a4184bddda2db4c63726

build:
  number: 0
  noarch: python
  entry_points:
    - pyhdx = pyhdx.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - hdxrate >=0.2.0
    - numpy
    - matplotlib-base ==3.4.3
    - pandas
    - scikit-image
    - scipy
    - symfit >=0.5.5
    - typer
    - param
    - pytorch
    - tqdm
    - dask
    - distributed
    - packaging
test:
  imports:
    - pyhdx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/PyHDX
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Derive Î”G for single residues from HDX-MS data
  doc_url: https://pyhdx.readthedocs.io/
  dev_url: https://github.com/Jhsmit/PyHDX

extra:
  recipe-maintainers:
    - Jhsmit
